# -*- coding: utf-8 -*-
"""Forecast_Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGuL1__yFZTyED3mdcUdehDHVY0QHgXJ

# **DỰ BÁO DOANH THU CHO NĂM TIẾP THEO**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from prophet import Prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar
from pandas.api.types import CategoricalDtype

import warnings
warnings.filterwarnings("ignore")

plt.style.use('ggplot')
plt.style.use('fivethirtyeight')

# Custom MAPE
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Đọc dữ liệu, parse ngày (Google Colab: /content/drive/MyDrive/NHÓM 11 - Big Data/Dataset/Dataclean.csv)
df = pd.read_csv('C:/Users/nny08/PycharmProjects/PythonProject2/Data Source/Dataclean.csv',
                 encoding='latin1', parse_dates=['order date (DateOrders)'])

# Đổi tên để dễ xử lý
df.rename(columns={'order date (DateOrders)': 'Datetime', 'Sales': 'Sales'}, inplace=True)

"""# **TÍNH SALES VÀ VẼ BIỂU ĐỒ**"""

# Tính tổng Sales theo từng ngày (giữ bước này của code mới)
daily_sales = df.groupby('Datetime')['Sales'].sum().reset_index()
daily_sales.set_index('Datetime', inplace=True)

# Vẽ biểu đồ chuỗi thời gian tổng Sales theo ngày
color_pal = sns.color_palette()
daily_sales['Sales'].plot(style='.', figsize=(10, 5), ms=3, color=color_pal[0], title='Daily Total Sales over Time')
plt.show()

"""# **TẠO ĐẶC TRƯNG THỜI GIAN CHO DỮ LIỆU**

"""

# Tạo đặc trưng thời gian dựa trên dữ liệu tổng Sales theo ngày
cat_type = CategoricalDtype(categories=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'], ordered=True)

def create_features(df, label=None):
    df = df.copy()
    df['date'] = df.index
    df['dayofweek'] = df['date'].dt.dayofweek
    df['weekday'] = df['date'].dt.day_name().astype(cat_type)
    df['quarter'] = df['date'].dt.quarter
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year
    df['dayofyear'] = df['date'].dt.dayofyear
    df['dayofmonth'] = df['date'].dt.day
    df['weekofyear'] = df['date'].dt.isocalendar().week.astype(int)
    df['date_offset'] = (df.date.dt.month*100 + df.date.dt.day - 320)%1300
    df['season'] = pd.cut(df['date_offset'], [0, 300, 602, 900, 1300], labels=['Spring', 'Summer', 'Fall', 'Winter'])

    X = df[['dayofweek','quarter','month','year','dayofyear','dayofmonth','weekofyear','weekday','season']]
    if label:
        y = df[label]
        return X, y
    return X

X, y = create_features(daily_sales, label='Sales')
features_and_target = pd.concat([X, y], axis=1)

"""# **VẼ BIỂU ĐỒ THEO TUẦN VÀ THEO MÙA**"""

# Boxplot Sales theo ngày trong tuần và mùa
fig, ax = plt.subplots(figsize=(10, 5))
sns.boxplot(data=features_and_target.dropna(), x='weekday', y='Sales', hue='season', ax=ax, linewidth=1)
ax.set_title('Sales by Day of Week and Season')
ax.set_xlabel('Day of Week')
ax.set_ylabel('Sales')
ax.legend(bbox_to_anchor=(1, 1))
plt.show()

"""# **CHIA TẬP TRAIN/TEST**"""

# Chia tập train-test theo ngày
split_date = '2017-12-31'  # train đến hết năm 2017
train = daily_sales.loc[daily_sales.index <= split_date].copy()
test = daily_sales.loc[daily_sales.index > split_date].copy()

# Chuẩn bị dữ liệu cho Prophet
train_prophet = train.reset_index().rename(columns={'Datetime':'ds', 'Sales':'y'})
test_prophet = test.reset_index().rename(columns={'Datetime':'ds', 'Sales':'y'})

# Train model Prophet (không có ngày lễ)
model = Prophet()
model.fit(train_prophet)

# Dự báo trên tập test
forecast = model.predict(test_prophet)

"""# **VẼ DỰ BÁO THỰC TẾ**"""

# Vẽ dự báo so với thực tế
plt.figure(figsize=(15,6))
plt.plot(train_prophet['ds'], train_prophet['y'], label='Train')
plt.plot(test_prophet['ds'], test_prophet['y'], label='Test Actual', color='red')
plt.plot(forecast['ds'], forecast['yhat'], label='Forecast')
plt.fill_between(forecast['ds'], forecast['yhat_lower'], forecast['yhat_upper'], color='blue', alpha=0.2)
plt.legend()
plt.title('Prophet Forecast vs Actual Sales')
plt.ylabel('Sales')
plt.xlabel('Date')
plt.show()

# In kết quả đo lường độ chính xác
print("Metrics for Prophet model without holidays:")
print("RMSE:", np.sqrt(mean_squared_error(test['Sales'], forecast['yhat'])))
print("MAE:", mean_absolute_error(test['Sales'], forecast['yhat']))
print("MAPE:", mean_absolute_percentage_error(test['Sales'], forecast['yhat']))

"""# **VẼ DỰ BÁO CÓ THÊM NGÀY LỄ**"""

# Thêm ngày lễ US Federal Holidays vào model
cal = calendar()
holidays = cal.holidays(start=daily_sales.index.min(), end=daily_sales.index.max(), return_name=True)
holiday_df = pd.DataFrame({'ds': holidays.index, 'holiday': holidays.values})

model_holidays = Prophet(holidays=holiday_df)
model_holidays.fit(train_prophet)

forecast_holidays = model_holidays.predict(test_prophet)

# Vẽ so sánh dự báo với thực tế (có ngày lễ)
plt.figure(figsize=(15,6))
plt.plot(train_prophet['ds'], train_prophet['y'], label='Train')
plt.plot(test_prophet['ds'], test_prophet['y'], label='Test Actual', color='red')
plt.plot(forecast_holidays['ds'], forecast_holidays['yhat'], label='Forecast with Holidays')
plt.fill_between(forecast_holidays['ds'], forecast_holidays['yhat_lower'], forecast_holidays['yhat_upper'], color='green', alpha=0.2)
plt.legend()
plt.title('Prophet Forecast with Holidays vs Actual Sales')
plt.ylabel('Sales')
plt.xlabel('Date')
plt.show()

print("Metrics for Prophet model with holidays:")
print("RMSE:", np.sqrt(mean_squared_error(test['Sales'], forecast_holidays['yhat'])))
print("MAE:", mean_absolute_error(test['Sales'], forecast_holidays['yhat']))
print("MAPE:", mean_absolute_percentage_error(test['Sales'], forecast_holidays['yhat']))

# Vẽ các thành phần của model với ngày lễ
model_holidays.plot_components(forecast_holidays)
plt.show()

"""# **VẼ BIỂU ĐỒ FORECAST VÀ THỰC TẾ**"""

# Vẽ chi tiết forecast vs actual trong tháng 1/2018
fig, ax = plt.subplots(figsize=(10, 5))
ax.scatter(test.index, test['Sales'], color='r')
model_holidays.plot(forecast_holidays, ax=ax)
ax.set_xbound(lower=pd.to_datetime('2018-01-01'), upper=pd.to_datetime('2018-01-31'))
ax.set_ylim(bottom=0)
plt.suptitle('Forecast with Holidays vs Actuals - Jan 2018')
plt.show()

"""# **DỰ BÁO CHO NĂM TIẾP THEO**"""

# Dự báo tương lai 365 ngày
future = model_holidays.make_future_dataframe(periods=365*2)
future_forecast = model_holidays.predict(future)

# Vẽ dự báo tương lai
plt.figure(figsize=(12,5))
model_holidays.plot(future_forecast)
plt.title('Future 2 Years Sales Forecast')
plt.show()